apiVersion: v1
kind: Namespace
metadata:
  name: ot-image
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ot-image
  namespace: ot-image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ot-image
  template:
    metadata:
      labels:
        app: ot-image
    spec:
      containers:
      - image: registry.velodemo.ninja/library/hmi:1
      
        name: ot-image
        imagePullPolicy: Always
        volumeMounts:
          - name: host-mount
            mountPath: /usbdrive
      volumes:
        - name: host-mount
          hostPath:
            path: /mnt/usbdrive        
